### ISSUE TITLE
แจ้งว่าช่วงนี้เว็บ https://ariabook.vercel.app/ เข้ายากค่ะ

### ISSUE THREAD

**Issue by eennap** [YaninL/Aria-Feedback#1]
มาแจ้งว่าช่วงนี้เว็บ https://ariabook.vercel.app/ เข้ายากค่ะ ต้องกด reload หลายรอบเลยค่ะ กว่าจะเข้าได้
ชอบเว็บนี้มากเลยนะคะ ทำ epub สวยมากค่ะ อยากให้เว็บอยู่นานๆ

**Comment by YaninL** [comment]
น่าจะโดนช่วงปิดปรับปรุงพอดีจ้า แก้ไขใหม่แล้ว
